### ISSUE TITLE
Configuring OpenID Connect IDP is failing

### ISSUE THREAD

**Issue by dipak-pawar** [openshift/cluster-authentication-operator#153]
**Steps to Reproduce**
- Install Openshift cluster 4.2
- Create Realm `toolchain-dev` and client `toolchain` for our own running keycloak.
- Create `OAuth`, `secret`, `user`, `identity`, `UserIdentityMapping` from following yaml files.
- When we try to login, we can see login with rhd, but failing with authentication error.

**Openshift version tried**
-  `4.2.0-0.okd-2019-07-22-044315`
-  ` 4.1.4`

**Pod logs**
```
I0723 15:16:22.650706       1 log.go:172] http: TLS handshake error from 10.128.2.16:51866: EOF
E0723 15:16:44.494035       1 errorpage.go:26] AuthenticationError: Code not valid
```

**Yaml manifest**
```yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: rhd
    mappingMethod: lookup
    type: OpenID
    openID:
      clientID: toolchain
      clientSecret:
        name: rhd-idp-secret
      claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      issuer: https://sso.prod-preview.openshift.io/auth/realms/toolchain-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: rhd-idp-secret
  namespace: openshift-config
type: Opaque
data:
  clientSecret: <replace_wih_secret>
---
apiVersion: user.openshift.io/v1
groups: null
identities: null
kind: User
metadata:
  name: ${USERNAME}
---
apiVersion: user.openshift.io/v1
kind: Identity
metadata:
  name: rhd:${USER_ID_FROM_SUB_CLAIM}
providerName: rhd
providerUserName: ${USER_ID_FROM_SUB_CLAIM}
---
apiVersion: user.openshift.io/v1
kind: UserIdentityMapping
metadata:
  name: rhd:${USER_ID_FROM_SUB_CLAIM}
user:
  name: ${USERNAME}
identity:
  name: rhd:${USER_ID_FROM_SUB_CLAIM}
```

Note:
1. This setup was working previously.(Not sure about the openshift version)
2. We need `mappingMethod: lookup` from OAuth configuration

cc @xcoulon  @alexeykazakov
