### ISSUE TITLE
x509: certificate signed by unknown authority error using keycloak operator

### ISSUE THREAD

**Issue by dkhachyan** [openshift/cluster-authentication-operator#390]
Hi!
We try to deploy keycloak as external identity provider via keycloak operator during openshift installation process.
Keycloak operator uses OpenShift [service-ca-operator](https://github.com/openshift/service-ca-operator) to generate service serving certificate as described [here](https://docs.openshift.com/container-platform/4.5/security/certificates/service-serving-certificate.html)

By default, authentication-operator does not trust certificates generated by service-ca-operator. 
It only trusts CAs located in  trusted-ca-bundle ConfigMap.
We have noticed that serving-cert CA has already mounted to authentication-operator pod.

Entrypoint args of authentication-operator:
```
if [ -s /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt ]; then
              echo "Copying system trust bundle"
              cp -f /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          fi
          exec authentication-operator operator --config=/var/run/configmaps/config/operator-config.yaml --v=2 --terminate-on-files=/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt
```

Perhaps we have to make serving-cert CA trusted by default instead of configuring ca section in the oauth config after deploying Keycloak instance:

```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: keycloak
    openID:
      ca:  <--- this section
        name:  <ConfigMap with keycloak certificate>
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: openshift
      clientSecret:
        name: openid-client-secret-djbhz
      extraScopes: []
      issuer: https://keycloak-url
    type: OpenID
```
For example we can add serving ca to tls-ca-bundle.pem:

```
if [ -s /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt ]; then
              echo "Copying system trust bundle"
              cp -f /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              echo "Copying service trust bundle"
              cat /var/run/configmaps/service-ca-bundle/service-ca.crt >> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          fi
          exec authentication-operator operator --config=/var/run/configmaps/config/operator-config.yaml --v=2 --terminate-on-files=/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt
```

Could you please suggest any better solution?
